// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_glass_block_smasher = "CgkIwe34nvoWEAIQBQ"; // <GPGSID>
        public const string achievement_100_bombs = "CgkIwe34nvoWEAIQAw"; // <GPGSID>
        public const string achievement_fast_man = "CgkIwe34nvoWEAIQAg"; // <GPGSID>
        public const string achievement_levels_in_a_row = "CgkIwe34nvoWEAIQDw"; // <GPGSID>
        public const string leaderboard_best_players = "CgkIwe34nvoWEAIQAQ"; // <GPGSID>
        public const string achievement_game_complete = "CgkIwe34nvoWEAIQCQ"; // <GPGSID>
        public const string achievement_combo_master_ii = "CgkIwe34nvoWEAIQBw"; // <GPGSID>
        public const string achievement_500_bombs = "CgkIwe34nvoWEAIQBA"; // <GPGSID>
        public const string achievement_rock_block_smasher = "CgkIwe34nvoWEAIQCA"; // <GPGSID>
        public const string achievement_combo_master = "CgkIwe34nvoWEAIQBg"; // <GPGSID>

}

